#!/bin/env bash
set -ex

OUT_DIR=out
GERBER_DIR=gerber
PROJECT_NAME=va4
ZIP_FILENAME="$PROJECT_NAME-gerbers.zip"

mkdir -p "$OUT_DIR"

cp "$GERBER_DIR/$PROJECT_NAME-F.Cu.gbr" "$OUT_DIR/$PROJECT_NAME.GTL"
cp "$GERBER_DIR/$PROJECT_NAME-B.Cu.gbr" "$OUT_DIR/$PROJECT_NAME.GBL"
cp "$GERBER_DIR/$PROJECT_NAME-F.Mask.gbr" "$OUT_DIR/$PROJECT_NAME.GTS"
cp "$GERBER_DIR/$PROJECT_NAME-B.Mask.gbr" "$OUT_DIR/$PROJECT_NAME.GBS"
cp "$GERBER_DIR/$PROJECT_NAME-F.SilkS.gbr" "$OUT_DIR/$PROJECT_NAME.GTO"
cp "$GERBER_DIR/$PROJECT_NAME-B.SilkS.gbr" "$OUT_DIR/$PROJECT_NAME.GBO"
cp "$GERBER_DIR/$PROJECT_NAME-PTH.drl" "$OUT_DIR/$PROJECT_NAME.TXT"
cp "$GERBER_DIR/$PROJECT_NAME-NPTH.drl" "$OUT_DIR/$PROJECT_NAME-NPTH.TXT"
cp "$GERBER_DIR/$PROJECT_NAME-Edge.Cuts.gbr" "$OUT_DIR/$PROJECT_NAME.GML"

if [ -e "$(which 7z)" ]; then
    pushd "$OUT_DIR"
        rm "$ZIP_FILENAME" || true
        7z a "$ZIP_FILENAME" "$PROJECT_NAME.GTL" "$PROJECT_NAME.GBL" "$PROJECT_NAME.GTS" "$PROJECT_NAME.GBS" "$PROJECT_NAME.GTO" "$PROJECT_NAME.GBO" "$PROJECT_NAME.TXT" "$PROJECT_NAME-NPTH.TXT" "$PROJECT_NAME.GML"
        7z l "$ZIP_FILENAME" 
    popd
else
    echo "Error: Could not find 7z exe." >&2
    exit 1
fi
